name: agixt_even_realities
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  get: ^4.6.6
  crclib: ^3.0.0
  fluttertoast: ^8.2.12
  agixtsdk: ^0.0.4
  flutter_svg: ^2.0.9
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  url_launcher: ^6.3.1
  http: ^1.3.0
  crypto: ^3.0.6
  font_awesome_flutter: ^10.8.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1 # Add google_fonts
  flutter_blue_plus: ^1.31.18 # Add flutter_blue_plus (check pub.dev for latest)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
