name: agixt_even_realities
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  get: ^4.6.6
  crclib: ^3.0.0
  fluttertoast: ^8.2.8
  agixtsdk: ^0.0.6
  flutter_svg: ^2.0.9
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0 # Added for opening OAuth URLs
  font_awesome_flutter: ^10.7.0 # Added for provider icons
  shared_preferences: ^2.2.2
  app_links: ^3.5.1 # Replaced uni_links for handling app links/OAuth callbacks
  shelf: ^1.4.1 # For local HTTP server
  shelf_router: ^1.1.4 # Router for shelf

  crypto: ^3.0.3 # For PKCE code generation
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
